package ui

const (
	EDITOR_MODE_NONE = iota
	EDITOR_NORMAL_MODE
	EDITOR_EDIT_MODE
	EDITOR_COMMAND_MODE

	EDITOR_ACTION_STATE_PREPARE_WRITE = iota
	EDITOR_ACTION_STATE_WRITE

	EDITOR_ACTION_TYPE_INSERT = iota
	EDITOR_ACTION_TYPE_DELETE
)
